const std = @import("std");
const types = @import("types.zig");
const log = std.log.scoped(.MessageHandlers);

/// KexInit has the following packet body
///     byte[16]     cookie (random bytes)
///    name-list    kex_algorithms
///     name-list    server_host_key_algorithms
///     name-list    encryption_algorithms_client_to_server
///     name-list    encryption_algorithms_server_to_client
///     name-list    mac_algorithms_client_to_server
///     name-list    mac_algorithms_server_to_client
///    name-list    compression_algorithms_client_to_server
///     name-list    compression_algorithms_server_to_client
///     name-list    languages_client_to_server
///     name-list    languages_server_to_client
///     boolean      first_kex_packet_follows
///     uint32       0 (reserved for future extension)
pub fn handleKexInit(reader: *std.Io.Reader, alloc: std.mem.Allocator) !types.KexInitPayload {
    // The 'cookie' MUST be a random value generated by the sender.
    // Its purpose is to make it impossible for either side to fully
    // determine the keys and the session identifier.
    return try types.KexInitPayload.parse(reader, alloc);
}
