const std = @import("std");
const utils = @import("../utils.zig");
pub const SshPacket = struct {
    packet_length: u32,
    padding_length: u8,
    payload: []const u8,
    mac: ?[]const u8 = null,

    pub fn format(self: SshPacket, w: *std.Io.Writer) !void {
        try w.print("{{ \n packet_length: {d}, \n padding_length: {d}, \n payload: {s}\n  mac: {s}\n  }}", .{ self.packet_length, self.padding_length, self.payload, utils.checkNullFormat(self.mac) });
        try w.flush();
    }
};

pub const NameList = struct {
    length: u32,
    names: []const []const u8,
    pub fn Parse(reader: *std.Io.Reader, alloc: std.mem.Allocator) !NameList {
        const log = std.log.scoped(.NameListParse);
        var name_list_length_array: [4]u8 = undefined;
        const read_bytes = try reader.readSliceShort(&name_list_length_array);
        std.debug.assert(read_bytes == 4);
        const name_list_length = std.mem.readInt(u32, &name_list_length_array, .big);
        log.info("name_list_length: {d}", .{name_list_length});
        const name_list = try reader.take(name_list_length);
        log.info("name_list: {s}", .{name_list});
        var names = try std.ArrayList([]const u8).initCapacity(alloc, 50);
        var it = std.mem.splitScalar(u8, name_list, ',');

        while (it.next()) |name| {
            try names.append(alloc, name);
        }
        return .{
            .length = name_list_length,
            .names = try names.toOwnedSlice(alloc),
        };
    }
    pub fn format(
        self: @This(),
        writer: *std.Io.Writer,
    ) std.Io.Writer.Error!void {
        try writer.print("[\n ", .{});
        for (self.names) |name| {
            try writer.print("\t{s},\n", .{name});
        }
        try writer.print("]\n", .{});
    }

    pub fn getFormatSendableNameList(self: NameList, alloc: std.mem.Allocator) ![]const u8 {
        var list = try std.ArrayList(u8).initCapacity(alloc, 1028);
        for (self.names) |value| {
            try list.print(alloc, "{s},", .{value});
        }
        // remove the last byte which is a ','
        const popped_comma = list.pop();
        std.debug.assert(popped_comma != null and popped_comma.? == ',');
        return try list.toOwnedSlice(alloc);
    }
};

pub const SSH_MSG = enum(u8) {
    disconnect = 1,
    ignore = 2,
    unimplemented = 3,
    debug = 4,
    service_request = 5,
    service_accept = 6,
    kexinit = 20,
    newkeys = 21,
    userauth_request = 50,
    userauth_failure = 51,
    userauth_success = 52,
    userauth_banner = 53,
    global_request = 80,
    request_success = 81,
    request_failure = 82,
    channel_open = 90,
    channel_open_confirmation = 91,
    channel_open_failure = 92,
    channel_window_adjust = 93,
    channel_data = 94,
    channel_extended_data = 95,
    channel_eof = 96,
    channel_close = 97,
    channel_request = 98,
    channel_success = 99,
    channel_failure = 100,
};

pub const KexInitPayload = struct {
    /// The 'cookie' MUST be a random value generated by the sender.
    /// Its purpose is to make it impossible for either side to fully
    /// determine the keys and the session identifier.
    cookie: []u8,
    /// Key exchange algorithms were defined above.  The first
    /// algorithm MUST be the preferred (and guessed) algorithm.  If
    /// both sides make the same guess, that algorithm MUST be used.
    /// Otherwise, the following algorithm MUST be used to choose a key
    /// exchange method: Iterate over client's kex algorithms, one at a
    /// time.  Choose the first algorithm that satisfies the following
    /// conditions:
    ///
    ///     +   the server also supports the algorithm,
    ///     +   if the algorithm requires an encryption-capable host key,
    ///         there is an encryption-capable algorithm on the server's
    ///         server_host_key_algorithms that is also supported by the
    ///         client, and
    ///     +   if the algorithm requires a signature-capable host key,
    ///         there is a signature-capable algorithm on the server's
    ///         server_host_key_algorithms that is also supported by the
    ///         client.
    ///
    /// If no algorithm satisfying all these conditions can be found, the
    /// connection fails, and both sides MUST disconnect.
    kex_algorithms: NameList,
    ///A name-list of the algorithms supported for the server host
    ///key.  The server lists the algorithms for which it has host
    ///keys; the client lists the algorithms that it is willing to
    ///accept.  There MAY be multiple host keys for a host, possibly
    ///with different algorithms.
    ///Some host keys may not support both signatures and encryption
    ///(this can be determined from the algorithm), and thus not all
    ///host keys are valid for all key exchange methods.
    ///Algorithm selection depends on whether the chosen key exchange
    ///algorithm requires a signature or an encryption-capable host
    ///key.  It MUST be possible to determine this from the public key
    ///algorithm name.  The first algorithm on the client's name-list
    ///that satisfies the requirements and is also supported by the
    ///server MUST be chosen.  If there is no such algorithm, both
    ///sides MUST disconnect.
    server_host_key_algorithms: NameList,
    /// A name-list of acceptable symmetric encryption algorithms (also
    ///   known as ciphers) in order of preference.  The chosen
    ///   encryption algorithm to each direction MUST be the first
    ///   algorithm on the client's name-list that is also on the
    ///   server's name-list.  If there is no such algorithm, both sides
    ///   MUST disconnect.
    ///   Note that "none" must be explicitly listed if it is to be
    ///    acceptable.  The defined algorithm names are listed in Section
    ///    6.3.
    encryption_algorithims_client_to_server: NameList,
    encryption_algorithims_server_to_client: NameList,
    /// A name-list of acceptable MAC algorithms in order of
    ///   preference.  The chosen MAC algorithm MUST be the first
    ///   algorithm on the client's name-list that is also on the
    ///   server's name-list.  If there is no such algorithm, both sides
    ///   MUST disconnect.
    ///   Note that "none" must be explicitly listed if it is to be
    ///   acceptable
    mac_algorithims_client_to_server: NameList,
    mac_algorithims_server_to_client: NameList,
    /// A name-list of acceptable compression algorithms in order of
    ///   preference.  The chosen compression algorithm MUST be the first
    ///    algorithm on the client's name-list that is also on the
    ///    server's name-list.  If there is no such algorithm, both sides
    ///    MUST disconnect.
    ///     Note that "none" must be explicitly listed if it is to be
    ///     acceptable.
    compression_algorithims_client_to_server: NameList,
    compression_algorithims_server_to_client: NameList,
    ///This is a name-list of language tags in order of preference
    ///  [RFC3066].  Both parties MAY ignore this name-list.  If there
    ///  are no language preferences, this name-list SHOULD be empty as
    ///  defined in Section 5 of [SSH-ARCH].  Language tags SHOULD NOT
    ///  be present unless they are known to be needed by the sending
    ///  party.
    languages_client_to_server: NameList,
    languages_server_to_client: NameList,
    ///Indicates whether a guessed key exchange packet follows.  If a
    ///     guessed packet will be sent, this MUST be TRUE.  If no guessed
    ///     packet will be sent, this MUST be FALSE.
    first_kex_parket_follows: bool = false,
    res: u32 = 0,
    pub fn parse(reader: *std.Io.Reader, alloc: std.mem.Allocator) !KexInitPayload {
        const log = std.log.scoped(.KexInitParser);
        const cookie: []u8 = try reader.take(16);
        log.info("cookie {s}", .{cookie});
        const kex_algo = try NameList.Parse(reader, alloc);
        log.info("kex_algo {f}", .{kex_algo});
        const server_host = try NameList.Parse(reader, alloc);
        log.info("server_host {f}", .{server_host});
        const encrypt_c_s = try NameList.Parse(reader, alloc);
        log.info("encrypt_c_s  {f}", .{encrypt_c_s});
        const encrypt_s_c = try NameList.Parse(reader, alloc);
        log.info("encrypt_s_c  {f}", .{encrypt_s_c});
        const mac_c_s = try NameList.Parse(reader, alloc);
        log.info("mac_c_s  {f}", .{mac_c_s});
        const mac_s_c = try NameList.Parse(reader, alloc);
        log.info("mac_s_c  {f}", .{mac_s_c});
        const compression_c_s = try NameList.Parse(reader, alloc);
        log.info("compression_c_s  {f}", .{compression_c_s});
        const compression_s_c = try NameList.Parse(reader, alloc);
        log.info("compression_s_c  {f}", .{compression_s_c});
        const lang_c_s = try NameList.Parse(reader, alloc);
        log.info("lang_c_s  {f}", .{lang_c_s});
        const lang_s_c = try NameList.Parse(reader, alloc);
        log.info("lang_s_c  {f}", .{lang_s_c});
        const packet_follows = (try reader.takeByte()) != 0;
        log.info("packet_follows = {}", .{packet_follows});
        var resLengthArray: [4]u8 = undefined;
        const readBytes = try reader.readSliceShort(&resLengthArray);
        std.debug.assert(readBytes == 4);
        const resLength = std.mem.readInt(u32, &resLengthArray, .big);
        log.info("res length gotten {d}\n", .{resLength});

        return .{
            .cookie = cookie,
            .kex_algorithms = kex_algo,
            .server_host_key_algorithms = server_host,
            .encryption_algorithims_client_to_server = encrypt_c_s,
            .encryption_algorithims_server_to_client = encrypt_s_c,
            .mac_algorithims_client_to_server = mac_c_s,
            .mac_algorithims_server_to_client = mac_s_c,
            .compression_algorithims_client_to_server = compression_c_s,
            .compression_algorithims_server_to_client = compression_s_c,
            .languages_client_to_server = lang_c_s,
            .languages_server_to_client = lang_s_c,
            .first_kex_parket_follows = packet_follows,
        };
    }
    pub fn format(
        self: @This(),
        writer: *std.Io.Writer,
    ) std.Io.Writer.Error!void {
        try writer.writeAll("Kex Payload {{\n");
        try writer.print("\tcookie: {s}\n", .{self.cookie});
        try writer.print("\tkex_algos: {f}\n", .{self.kex_algorithms});
        try writer.print("\tserver_host_algos: {f}\n", .{self.server_host_key_algorithms});
        try writer.print("\tenc_c_s: {f}\n", .{self.encryption_algorithims_client_to_server});
        try writer.print("\tenc_s_c: {f}\n", .{self.encryption_algorithims_server_to_client});
        try writer.print("\tmac_c_s: {f}\n", .{self.mac_algorithims_client_to_server});
        try writer.print("\tmac_s_c: {f}\n", .{self.mac_algorithims_server_to_client});
        try writer.print("\tcomp_c_s: {f}\n", .{self.compression_algorithims_client_to_server});
        try writer.print("\tcomp_s_c: {f}\n", .{self.compression_algorithims_server_to_client});
        try writer.print("\tlang_c_s: {f}\n", .{self.languages_client_to_server});
        try writer.print("\tlang_s_c: {f}\n", .{self.languages_server_to_client});
        try writer.print("\tfirst_kex: {}\n", .{self.first_kex_parket_follows});

        try writer.writeAll(" }}\n");
    }
};
